# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: "18.x"
  AZURE_WEBAPP_NAME: "nodeapp"
  RESOURCE_GROUP: "my-node-app-rg"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Build
        run: npm run build
        working-directory: backend

      - name: Run tests
        run: npm test
        working-directory: backend

      - name: Prepare deployment
        run: npm run prepare-deployment
        working-directory: backend

      - name: Zip artifact for deployment
        run: |
          cd backend
          mkdir -p deployment
          cp -r dist/* deployment/
          cp web.config deployment/ || true
          cp package.json deployment/
          cp startup.sh deployment/ || true
          chmod +x deployment/startup.sh || true
          cd deployment
          zip -r ../../deploy.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E2606AAA9E5E48FF8CF66B6706BEE255 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7AAD3F825C2D41D8BE7CAD38C70D2451 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_625B6336EF244756A94B7EC3FC023742 }}

      # Configure Azure App Service
      - name: Configure Azure App Service
        run: |
          # Set Node.js version
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --settings WEBSITE_NODE_DEFAULT_VERSION=~18 \
            PORT=8080 \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true

          # Configure startup command to use our startup script
          az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --startup-file startup.sh

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          slot-name: "Production"
          package: ./deploy.zip
